name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read # for checkout
  # Required to put a comment into the pull-request
  pull-requests: write

jobs:
  test:
    timeout-minutes: 60
    name: Test (${{ matrix.os-version }} / node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os-version }}
    strategy:
      # we want to know if a test fails on a specific node version
      fail-fast: false
      matrix:
        os-version: [ubuntu-latest]
        node-version: [lts/-1, lts/*]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: |
          node -v
          npx vitest run --typecheck --coverage.enabled=true
      - name: 'Report Coverage'
        # Set if: always() to also generate the report if tests are failing
        # Only works if you set `reportOnFailure: true` in your vite config as specified above
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
