name: Lint

on:
  pull_request:
  push:
    branches: ['**']


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [18, 20]

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Test
      id: test
      run: |
        node -v
        pnpm test