name: Typecheck

on:
  pull_request:
  push:
    branches: ['**']

jobs:
  lint:
    timeout-minutes: 10
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3

      - name: Install project dependencies
        run: npm install --ci

      - name: Typecheck
        id: typecheck
        run: |
          node -v
          npm -v
          npm run typecheck
          npm run typecheck:examples
