name: Typecheck

on:
  pull_request:
  push:
    branches: ['**']


jobs:
  lint:
    timeout-minutes: 10
    name: Typecheck
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [20]

    steps:
    - uses: actions/checkout@v4

    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'

    - name: Install dependencies
      run: pnpm install

    - name: Typecheck
      id: typecheck
      run: |
        node -v
        pnpm run typecheck
        pnpm run typecheck:examples
